apiVersion: apps/v1
kind: Deployment
metadata:
  name: globus-controller
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: globus-controller
  template:
    metadata:
      labels:
        app: globus-controller
    spec:
      imagePullSecrets:
      - name: default-secret
      serviceAccountName: globus-sa
      containers:
        - name: controller
          # REPLACE THIS WITH YOUR IMAGE
          image: artifactory.rafael.co.il:5012/rafael/health-sentinel:0.0.3
          imagePullPolicy: Always
          
          # Load config from the ConfigMap above
          envFrom:
            - configMapRef:
                name: globus-config
          
          # Resources for a lightweight Go controller
          resources:
            requests:
              cpu: "50m"
              memory: "32Mi"
            limits:
              cpu: "100m"
              memory: "64Mi"