apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-stratego
  namespace: default
spec:
  replicas: 2 # Small number for testing
  selector:
    matchLabels:
      app: dummy-stratego # Matches the Globus Controller target
  template:
    metadata:
      labels:
        app: dummy-stratego
        ofir: true
    spec:
      readinessGates:
        - conditionType: "controller.globus/swagger-ready" # Matches the Controller logic
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80