apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "readiness-controller.fullname" . }}-config
  labels:
    {{- include "readiness-controller.labels" . | nindent 4 }}
data:
  gates.json: |
    {{- .Values.probes | toJson | nindent 4 }}